<%@ Page Title="Edit Users"
    Language="C#"
    MasterPageFile="~/Site.Master"
    AutoEventWireup="true"
    CodeBehind="Users.aspx.cs"
    Inherits="TheCodeBookProject.Web.App.Admin.Users" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center alert alert-dismissable alert-success">Users Grid</h3>

            <asp:GridView CssClass="table table-striped table-hover table-bordered table-responsive"
                ID="gvUsers" runat="server"
                AutoGenerateSelectButton="true"
                SelectMethod="gvUsers_GetData"
                AutoGenerateEditButton="true"
                UpdateMethod="gvUsers_UpdateItem"
                AutoGenerateDeleteButton="true"
                DeleteMethod="gvUsers_DeleteItem"
                ItemType="TheCodeBookProject.Data.Models.User"
                AllowPaging="True" AllowSorting="True"
                DataKeyNames="Id"
                AutoGenerateColumns="false">
                <Columns>
                    <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName"></asp:BoundField>
                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email"></asp:BoundField>
                    <asp:BoundField DataField="FirstName" HeaderText="First name" SortExpression="FirstName"></asp:BoundField>
                    <asp:BoundField DataField="LastName" HeaderText="Last name" SortExpression="LastName"></asp:BoundField>
                    <asp:BoundField DataField="Rating" HeaderText="Rating" SortExpression="Rating"></asp:BoundField>
                    <asp:BoundField DataField="Votes" HeaderText="Votes" SortExpression="Votes"></asp:BoundField>
                    <asp:BoundField DataField="Knowledge" HeaderText="Knowledge" SortExpression="Knowledge"></asp:BoundField>
                    <asp:BoundField DataField="Skills" HeaderText="Skills" SortExpression="Skills"></asp:BoundField>
                    <asp:BoundField DataField="MyCompany.Name" HeaderText="Company" SortExpression="MyCompany"></asp:BoundField>
                    <asp:BoundField DataField="ImageUrl" HeaderText="Image Url" SortExpression="ImageUrl"></asp:BoundField>
                    <asp:CheckBoxField DataField="IsDeactivated" HeaderText="Deactivated" SortExpression="IsDeactivated" />
                </Columns>
            </asp:GridView>
        </div>
    </div>
</asp:Content>
